config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'avail_date', to: 'bookings#avail_date'
  namespace :charts do
    get 'new_user'
    get 'show_category'
    get 'show_hotel'
  end
  # devise_for :users, :controllers => {:registrations => "users/registrations"}
  resources :filters
  
  resources :room_bookings do
    # get 'user_index', on: :collection, action: :user_index
  end
  get '/room_bookings/user_index/:id' => 'room_bookings#user_index', as: :user_index
  get 'show_room',to: "bookings#show_room"
  resources :bookings
  # get 'bookings', to: 'bookings#confirm'
  resources :categories

  resources :hotels do
    resources :reviews, except: [:show, :index]
    resources :rooms, shallow: true do
    end
  end
  # get 'rooms/new_room/:hotel_id' => "rooms#create", as: :new_room
  resources :locations
  root to: 'users#home'
  get 'users', to: 'users#show'
  get 'charts', to: 'users#insight'
  devise_for :users
  resources :charges
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.has_role? :admin
      can :manage, :all
    elsif user.has_role? :hotelowner
      can :update, Hotel
      can :manage, Room
    else user.has_role? :customer
         can :read, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/booking.rb
# frozen_string_literal: true

class Booking < ApplicationRecord
  has_many :room_bookings, dependent: :destroy
  belongs_to :user
  has_many :rooms, through: :room_bookings

  accepts_nested_attributes_for :room_bookings, reject_if: :all_blank, allow_destroy: true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :rooms, dependent: :destroy
  def room_price
    category.price.to_s
  end
end

app/models/filter.rb
# frozen_string_literal: true

class Filter < ApplicationRecord
end

app/models/hotel.rb
# frozen_string_literal: true

class Hotel < ApplicationRecord
  belongs_to :user
  belongs_to :location
  has_many_attached :images
  has_many :rooms, dependent: :destroy
  has_many :reviews
  def thumbnail(input)
    images[input].variant(resize: '600x300!').processed
  end

  belongs_to :location
  def self.search(search)
    if search
      where(['name LIKE ?', "%#{search}%"])
    else
      all
    end
  end
end

app/models/location.rb
# frozen_string_literal: true

class Location < ApplicationRecord
  has_many :hotels
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user
    belongs_to :hotel
end

app/models/role.rb
# frozen_string_literal: true

class Role < ApplicationRecord
  has_and_belongs_to_many :users, join_table: :users_roles

  belongs_to :resource,
             polymorphic: true,
             optional: true

  validates :resource_type,
            inclusion: { in: Rolify.resource_types },
            allow_nil: true

  scopify
end

app/models/room.rb
# frozen_string_literal: true

class Room < ApplicationRecord
  belongs_to :hotel
  has_many :room_bookings, dependent: :destroy
  has_many :bookings, through: :room_bookings
  belongs_to :category
  # attr_accessor :category_name

  # def category_name
  #   category.name
  # end

  def display_room
    room_number.to_s + '(' + category.name + ')' + '(' + 'price' + category.price.to_s + ')'
  end
  # belongs_to :room
  # accepts_nested_attributes_for :room, reject_if: :all_blank, allow_destroy: true
  scope :available_rooms, -> { where(availibility: true) }
end

app/models/room_booking.rb
# frozen_string_literal: true

class RoomBooking < ApplicationRecord
  belongs_to :booking
  belongs_to :room
  validates :check_in, presence: true
  validates :check_out, presence: true
  before_create :avail

  def avail; end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  rolify
  resourcify
  # include Authority::UserAbilities
  has_many :bookings, dependent: :destroy
  has_many :hotels
  has_many :reviews, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create :assign_default_role

  def assign_default_role
    add_role(:customer) if roles.blank?
  end

  def destroy
    update_attributes(deactivated: true) unless deactivated
    end

  def active_for_authentication?
    super && !deactivated
      end
end

app/models/users_role.rb
# frozen_string_literal: true

class UsersRole < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/controllers/room_bookings_controller.rb
# frozen_string_literal: true

class RoomBookingsController < ApplicationController
  before_action :set_room_booking, only: %i[show edit update destroy]

  # GET /room_bookings
  # GET /room_bookings.json
  def index
    @room_bookings = RoomBooking.all.paginate(per_page: 5, page: params[:page])
  end

  def user_index
    booking = Booking.where(user_id: current_user.id)
    @room_bookings = RoomBooking.where(booking: booking)
  end

  # GET /room_bookings/1
  # GET /room_bookings/1.json
  def show
   end

  # GET /room_bookings/new
  def new
    @room_booking = RoomBooking.new
  end

  # GET /room_bookings/1/edit
  def edit; end

  # POST /room_bookings
  # POST /room_bookings.json
  def create
    @room_booking = RoomBooking.new(room_booking_params)

    respond_to do |format|
      if @room_booking.save
        format.html { redirect_to @room_booking, notice: 'Room booking was successfully created.' }
        format.json { render :show, status: :created, location: @room_booking }
      else
        format.html { render :new }
        format.json { render json: @room_booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /room_bookings/1
  # PATCH/PUT /room_bookings/1.json
  def update
    respond_to do |format|
      if @room_booking.update(room_booking_params)
        format.html { redirect_to @room_booking, notice: 'Room booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @room_booking }
      else
        format.html { render :edit }
        format.json { render json: @room_booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /room_bookings/1
  # DELETE /room_bookings/1.json
  def destroy
    @room_booking.destroy
    respond_to do |format|
      format.html { redirect_to room_bookings_url, notice: 'Room booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_room_booking
    @room_booking = RoomBooking.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def room_booking_params
    params.require(:room_booking).permit(:check_in, :check_out, :booking_id, :room_id)
  end
end

app/helpers/bookings_helper.rb
# frozen_string_literal: true

module BookingsHelper
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/filters_helper.rb
# frozen_string_literal: true

module FiltersHelper
end

app/helpers/hotels_helper.rb
# frozen_string_literal: true

module HotelsHelper
end

app/helpers/locations_helper.rb
# frozen_string_literal: true

module LocationsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/room_bookings_helper.rb
# frozen_string_literal: true

module RoomBookingsHelper
end

app/helpers/rooms_helper.rb
# frozen_string_literal: true

module RoomsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/room_bookings/_form.html.erb
<%= form_with(model: room_booking, local: true) do |form| %>
<% if room_booking.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(room_booking.errors.count, "error") %> prohibited this room_booking from being saved:</h2>

  <ul>
    <% room_booking.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="nested-fields">
  <div class="field">
    <%= form.label :check_in %>
    <%= form.datetime_select :check_in %>
  </div>

  <div class="field">
    <%= form.label :check_out %>
    <%= form.datetime_select :check_out %>
  </div>

  <div class="field">
   <%= form.collection_select :category_ids, Category.all,:id,:name, include_blank: false %>
   
 </div>
 <div>

  <%= link_to_remove_association "remove bookings", form %>
</div>
</div>

<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/room_bookings/edit.html.erb
<h1>Editing Room Booking</h1>

<%= render 'form', room_booking: @room_booking %>

<%= link_to 'Show', @room_booking %> |
<%= link_to 'Back', room_bookings_path %>

app/views/room_bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-success text-center">Room Bookings</h1>

<table class="table">
  <thead class="bg-success">
    <tr>
      <th>Email</th>
      <th>Hotel</th>
      <th>Check in</th>
      <th>Check out</th>
      <th>Room</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @room_bookings.each do |room_booking| %>
      <tr>
        <td><%= room_booking.booking.user.email %></td>
        <td><%= room_booking.room.hotel.name %></td>
        <td><%= room_booking.check_in %></td>
        <td><%= room_booking.check_out %></td>
        <td><%= room_booking.room.room_number %></td>
        <td><%= room_booking.room.category.name %></td>
        <td><%= link_to 'Show', room_booking %></td>
        <td><%= link_to 'Edit', edit_room_booking_path(room_booking) %></td>
        <td><%= link_to 'Destroy', room_booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  
<br>

<div class="digg_pagination">
<div class="page_info">
<%= page_entries_info @bookings %>
</div>
<%= will_paginate @room_bookings, renderer: BootstrapPagination::Rails %>
</div>

app/views/room_bookings/new.html.erb
<h1>New Room Booking</h1>

<%= render 'form', room_booking: @room_booking %>

<%= link_to 'Back', room_bookings_path %>

app/views/room_bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Check in:</strong>
  <%= @room_booking.check_in %>
</p>

<p>
  <strong>Check out:</strong>
  <%= @room_booking.check_out %>
</p>

<p>
  <strong>Booking:</strong>
  <%= @room_booking.booking_id %>
</p>

<p> 
  <strong>Room:</strong>
  <%= @room_booking.room_id %>
</p>

<%= link_to 'Edit', edit_room_booking_path(@room_booking) %> |
<%= link_to 'Back', room_bookings_path %>

app/views/room_bookings/user_index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center text-success">Your Bookings</h1>

<br/>
<br>
<table class="table">
  <thead class="bg-success">
    <tr>
      <th>Email</th>
      <th>Hotel name</th>
      <th>Check in</th>
      <th>Check out</th>
      <th>Room</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @room_bookings.each do |room_booking| %>
      <tr>
        <td><%= room_booking.booking.user.email %></td>
        <td><%= room_booking.room.hotel.name %></td>
        <td><%= room_booking.check_in %></td>
        <td><%= room_booking.check_out %></td>
        <td><%= room_booking.room.room_number %></td>
        <td><%= room_booking.room.category.name %></td>
       <!--  <td><%#= link_to 'Show', room_booking %></td>
        <td><%#= link_to 'Edit', edit_room_booking_path(room_booking) %></td>
        <td><%#= link_to 'Destroy', user_index_pat(:id), method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>
  <%= link_to 'New Room Booking', new_booking_path(params[:id]) , class: "btn btn-success" %>
<br>