config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'avail_date', to: 'bookings#avail_date'
  namespace :charts do
    get 'new_user'
    get 'show_category'
    get 'show_hotel'
  end
  # devise_for :users, :controllers => {:registrations => "users/registrations"}
  resources :filters
  
  resources :room_bookings do
    # get 'user_index', on: :collection, action: :user_index
  end
  get '/room_bookings/user_index/:id' => 'room_bookings#user_index', as: :user_index
  get 'show_room',to: "bookings#show_room"
  resources :bookings
  # get 'bookings', to: 'bookings#confirm'
  resources :categories

  resources :hotels do
    resources :reviews, except: [:show, :index]
    resources :rooms, shallow: true do
    end
  end
  # get 'rooms/new_room/:hotel_id' => "rooms#create", as: :new_room
  resources :locations
  root to: 'users#home'
  get 'users', to: 'users#show'
  get 'charts', to: 'users#insight'
  devise_for :users
  resources :charges
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.has_role? :admin
      can :manage, :all
    elsif user.has_role? :hotelowner
      can :update, Hotel
      can :manage, Room
    else user.has_role? :customer
         can :read, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
# frozen_string_literal: true

class Booking < ApplicationRecord
  has_many :room_bookings, dependent: :destroy
  belongs_to :user
  has_many :rooms, through: :room_bookings

  accepts_nested_attributes_for :room_bookings, reject_if: :all_blank, allow_destroy: true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :rooms, dependent: :destroy
  def room_price
    category.price.to_s
  end
end

app/models/filter.rb
# frozen_string_literal: true

class Filter < ApplicationRecord
end

app/models/hotel.rb
# frozen_string_literal: true

class Hotel < ApplicationRecord
  belongs_to :user
  belongs_to :location
  has_many_attached :images
  has_many :rooms, dependent: :destroy
  has_many :reviews
  def thumbnail(input)
    images[input].variant(resize: '600x300!').processed
  end

  belongs_to :location
  def self.search(search)
    if search
      where(['name LIKE ?', "%#{search}%"])
    else
      all
    end
  end
end

app/models/location.rb
# frozen_string_literal: true

class Location < ApplicationRecord
  has_many :hotels
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user
    belongs_to :hotel
end

app/models/role.rb
# frozen_string_literal: true

class Role < ApplicationRecord
  has_and_belongs_to_many :users, join_table: :users_roles

  belongs_to :resource,
             polymorphic: true,
             optional: true

  validates :resource_type,
            inclusion: { in: Rolify.resource_types },
            allow_nil: true

  scopify
end

app/models/room.rb
# frozen_string_literal: true

class Room < ApplicationRecord
  belongs_to :hotel
  has_many :room_bookings, dependent: :destroy
  has_many :bookings, through: :room_bookings
  belongs_to :category
  # attr_accessor :category_name

  # def category_name
  #   category.name
  # end

  def display_room
    room_number.to_s + '(' + category.name + ')' + '(' + 'price' + category.price.to_s + ')'
  end
  # belongs_to :room
  # accepts_nested_attributes_for :room, reject_if: :all_blank, allow_destroy: true
  scope :available_rooms, -> { where(availibility: true) }
end

app/models/room_booking.rb
# frozen_string_literal: true

class RoomBooking < ApplicationRecord
  belongs_to :booking
  belongs_to :room
  validates :check_in, presence: true
  validates :check_out, presence: true
  before_create :avail

  def avail; end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  rolify
  resourcify
  # include Authority::UserAbilities
  has_many :bookings, dependent: :destroy
  has_many :hotels
  has_many :reviews, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create :assign_default_role

  def assign_default_role
    add_role(:customer) if roles.blank?
  end

  def destroy
    update_attributes(deactivated: true) unless deactivated
    end

  def active_for_authentication?
    super && !deactivated
      end
end

app/models/users_role.rb
# frozen_string_literal: true

class UsersRole < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show; end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :price, :description)
  end
end

app/helpers/bookings_helper.rb
# frozen_string_literal: true

module BookingsHelper
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/filters_helper.rb
# frozen_string_literal: true

module FiltersHelper
end

app/helpers/hotels_helper.rb
# frozen_string_literal: true

module HotelsHelper
end

app/helpers/locations_helper.rb
# frozen_string_literal: true

module LocationsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/rooms_helper.rb
# frozen_string_literal: true

module RoomsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: [@category], local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div style="width: 340px;
margin: 50px auto;">
<div class="card">
  <h5 class="card-header info-color white-text text-center py-4">
    <strong class="text-success">your hotel categories</strong>
  </h5>
  <div class="card-body px-lg-5 pt-0">
  <div class="text-center">

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<% if user_signed_in? && current_user.admin %>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>
<% end %>

app/views/categories/index.html.erb
<% if user_signed_in? && current_user.admin %>
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table class="table">
  <thead class="bg-success">
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.price %></td>
        <td><%= category.description %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path, class: "btn btn-outline-success my-2 my-sm-0" %>
<% end %>

app/views/categories/new.html.erb
<% if user_signed_in? && current_user.admin %>
<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>
<% end %>

app/views/categories/show.html.erb
<% if user_signed_in? && current_user.admin %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @category.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>
<% end %>