config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'avail_date', to: 'bookings#avail_date'
  namespace :charts do
    get 'new_user'
    get 'show_category'
    get 'show_hotel'
  end
  # devise_for :users, :controllers => {:registrations => "users/registrations"}
  resources :filters
  
  resources :room_bookings do
    # get 'user_index', on: :collection, action: :user_index
  end
  get '/room_bookings/user_index/:id' => 'room_bookings#user_index', as: :user_index
  get 'show_room',to: "bookings#show_room"
  resources :bookings
  # get 'bookings', to: 'bookings#confirm'
  resources :categories

  resources :hotels do
    resources :reviews, except: [:show, :index]
    resources :rooms, shallow: true do
    end
  end
  # get 'rooms/new_room/:hotel_id' => "rooms#create", as: :new_room
  resources :locations
  root to: 'users#home'
  get 'users', to: 'users#show'
  get 'charts', to: 'users#insight'
  devise_for :users
  resources :charges
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/hotel.rb
# frozen_string_literal: true

class Hotel < ApplicationRecord
  belongs_to :user
  belongs_to :location
  has_many_attached :images
  has_many :rooms, dependent: :destroy
  has_many :reviews
  def thumbnail(input)
    images[input].variant(resize: '600x300!').processed
  end

  belongs_to :location
  def self.search(search)
    if search
      where(['name LIKE ?', "%#{search}%"])
    else
      all
    end
  end
end

app/controllers/hotels_controller.rb
# frozen_string_literal: true

class HotelsController < ApplicationController
  before_action :set_hotel, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[show index]
  # GET /hotels
  # GET /hotels.json
  def index
    @hotels = Hotel.search(params[:search]).paginate(per_page: 3, page: params[:page])
  end

  # GET /hotels/1
  # GET /hotels/1.json
  def show
  @reviews = Review.where(hotel_id: @hotel.id).order("created_at DESC")
    if @reviews.blank?
      @avg_review = 0
    else
      @avg_review = @reviews.average(:rating).round(2)
    end
  end

  # GET /hotels/new
  def new
    #@hotel = Hotel.new
    @hotel = current_user.hotels.build
  end

  # GET /hotels/1/edit
  def edit; end

  # POST /hotels
  # POST /hotels.json
  def create
    @hotel = current_user.hotels.build(hotel_params)
   # @hotel = Hotel.new(hotel_params)
    @hotel_owner = User.new
    @hotel_owner.email = "#{@hotel.name}@gmail.com"
    @hotel_owner.password = 'hotelowner123'

    respond_to do |format|
      if @hotel.save && @hotel_owner.save
        @hotel_owner.add_role :hotelowner
        format.html { redirect_to @hotel, notice: 'Hotel was successfully created.' }
        format.json { render :show, status: :created, location: @hotel }
      else
        format.html { render :new }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotels/1
  # PATCH/PUT /hotels/1.json
  def update
    respond_to do |format|
      if @hotel.update(hotel_params)
        format.html { redirect_to @hotel, notice: 'Hotel was successfully updated.' }
        format.json { render :show, status: :ok, location: @hotel }
      else
        format.html { render :edit }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1
  # DELETE /hotels/1.json
  def destroy
    @hotel.destroy
    respond_to do |format|
      format.html { redirect_to hotels_url, notice: 'Hotel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_hotel
    @hotel = Hotel.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def hotel_params
    params.require(:hotel).permit(:name, :address, :location_id, images: [])
  end
end

app/helpers/hotels_helper.rb
# frozen_string_literal: true

module HotelsHelper
end

app/views/hotels/_form.html.erb
<%= form_with(model: hotel, local: true) do |form| %>
<% if hotel.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(hotel.errors.count, "error") %> prohibited this hotel from being saved:</h2>

  <ul>
    <% hotel.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div style="width: 340px;
margin: 50px auto;">
<div class="card">
  <h5 class="card-header info-color white-text text-center py-4">
    <strong class="text-success">your hotel</strong>
  </h5>
  <div class="card-body px-lg-5 pt-0">
  <div class="text-center">

<div class="field">
  <%= form.label :name %>
  <%= form.text_field :name %>
</div>

<div class="field">
  <%= form.label :address %>
  <%= form.text_area :address %>
</div>

<div class="field">
  <%= form.label :images %>
  <%= form.file_field :images, multiple: true %>
</div>
<br/>
<div class="field">
  <%#= select("location", "location_id", Location.all.collect {|l| [ l.city, l.id ] }, { include_blank: true }) %>
  <%= form.collection_select :location_id, Location.all,:id,:city, include_blank: false %>
</div>
<br/>
<%#= link_to 'Add Rooms', new_room_path %>

<%# <%= redirect_to '/category/new' %>
<div class="actions">
  <%= form.submit %>
</div>
<% end %> 

app/views/hotels/edit.html.erb
<%= render 'form', hotel: @hotel %>

<%= link_to 'Show', @hotel %> |
<%= link_to 'Back', hotels_path %>

app/views/hotels/index.html.erb
<p id="notice"><%= notice %></p>


<div class="d-flex bd-highlight">

  <%= form_tag hotels_path, :method => 'get', class: "form-inline"  do %>
  <div class="p-2 bd-highlight">
    <%= text_field_tag :search, params[:search], class: "form-control form-control-sm ml-3 w-75", type: "text", placeholder: "Search" %>
  </div>
  <div class="p-2 bd-highlight l-3">
    <%= submit_tag "search", class: "btn btn-success" %>
  </div>
</div>
<% end %>
<br>
<h1><%= link_to "advance filter!", new_filter_path, class: "btn btn-warning" %></h1>
<br>
<table class="table">
  <thead class="thead bg-success">
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Location</th>
      <!-- <th>Rating</th> -->
      <th>Show</th>
      <% if current_user && current_user.admin %>
      <th>Edit</th>
      <th>Destroy</th>
  
      <% end %>
      
    </tr>
  </thead>

  <tbody>
    <% @hotels.each do |hotel| %>
    <tr>
      <td><%= hotel.name %></td>
      <td><%= hotel.address %></td>
      <td><%= hotel.location.city %></td>  
      <!-- <td><%#= rating_for @hotel, 'name', star: 10 %></td> -->
       <td><%= link_to 'Show', hotel %></td>
      <% if current_user && current_user.admin %>
      <td><%= link_to 'Edit', edit_hotel_path(hotel) %></td>
      <td><%= link_to 'Destroy', hotel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      
      
     

      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>


<% if current_user && current_user.admin  %>
<%= link_to 'New Hotel', new_hotel_path , class: "btn btn-outline-success my-2 my-sm-0"%> 
<% end %>
<br/>
<div><br/></div>

    <div class="digg_pagination">
        <div class="page_info">
            <%= page_entries_info @bookings %>
        </div>
            <%= will_paginate @hotels, renderer: BootstrapPagination::Rails %>
  </div>

app/views/hotels/new.html.erb
<%= render 'form', hotel: @hotel %>

<%= link_to 'Back', hotels_path %>

app/views/hotels/show.html.erb
<table class="table table-success">
<thead>
    <tr>
      <th scope="col">Name:</th>
      <th scope="col"><%= @hotel.name %></th>
      
    </tr>
</thead>
<tr>
      <th scope="col">Rating:</th>
      	<td class="star-rating" data-score= <%= @avg_review %> ></td> 
</tr>      
	<tr>
	<td scope="col">Address:</td>
	<td scope="col"><%= @hotel.address %></td>
</tr>
<tr>
	<td scope="col">Location:</td>
	<td scope="col"><%= @hotel.location.city%></td>
	</tr>
</table>
<% if @hotel.images.present? %>
<p>
	<% (0...@hotel.images.count).each do |image| %>
	<%= image_tag(@hotel.thumbnail(image)) %>
	<% end %>
</p>

<% else %>
<p> Image not uploaded </p>
<% end %>

<p>
<% if current_user && current_user.admin %>
<%= link_to 'add room details!',hotel_rooms_path(@hotel) ,  class: "btn btn-outline-success my-2 my-sm-0" %>
<% end %>
</p>

<% if current_user %>
<%= link_to 'book now!', user_index_path , class: "btn btn-outline-success my-2 my-sm-0" %>
<%= link_to "write reviews", new_hotel_review_path(@hotel),class: "btn btn-success" %>
<% else %>
<h3 class="text-danger">You need to login for booking.</h3>
<% end %>
<% if current_user && current_user.admin %>
<br/>
<br/>
<%= link_to 'Edit', edit_hotel_path(@hotel),class: "btn btn-outline-success my-2 my-sm-0" %> 
<% end %>
<br>
<br/>




	<div class="bg-light">
		<% if @reviews.blank? %>
			<h3>No reviews yet</h3>
		<% else %>
		<table class="table">
			 <h1 class="text-success"><%= "#{@reviews.length} reviews"%></h1>
			<% @reviews.each do |review| %>
				<p class="text-success"><%= review.user.email %></p>
				<div class="reviews">
				<div class="star-rating" data-score=<%= review.rating %> ></div> 
				<p><%= review.comment %></p>
				</div>
			<% end %>
		<% end %>
	</div>
	</table>


<%= link_to 'Back', hotels_path ,class: "btn btn-outline-success my-2 my-sm-0"%>


<script>
	$('.star-rating').raty({
		path: '/assets/',
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		}			
	});
</script>