config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'avail_date', to: 'bookings#avail_date'
  namespace :charts do
    get 'new_user'
    get 'show_category'
    get 'show_hotel'
  end
  # devise_for :users, :controllers => {:registrations => "users/registrations"}
  resources :filters
  
  resources :room_bookings do
    # get 'user_index', on: :collection, action: :user_index
  end
  get '/room_bookings/user_index/:id' => 'room_bookings#user_index', as: :user_index
  get 'show_room',to: "bookings#show_room"
  resources :bookings
  # get 'bookings', to: 'bookings#confirm'
  resources :categories

  resources :hotels do
    resources :reviews, except: [:show, :index]
    resources :rooms, shallow: true do
    end
  end
  # get 'rooms/new_room/:hotel_id' => "rooms#create", as: :new_room
  resources :locations
  root to: 'users#home'
  get 'users', to: 'users#show'
  get 'charts', to: 'users#insight'
  devise_for :users
  resources :charges
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.has_role? :admin
      can :manage, :all
    elsif user.has_role? :hotelowner
      can :update, Hotel
      can :manage, Room
    else user.has_role? :customer
         can :read, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/booking.rb
# frozen_string_literal: true

class Booking < ApplicationRecord
  has_many :room_bookings, dependent: :destroy
  belongs_to :user
  has_many :rooms, through: :room_bookings

  accepts_nested_attributes_for :room_bookings, reject_if: :all_blank, allow_destroy: true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :rooms, dependent: :destroy
  def room_price
    category.price.to_s
  end
end

app/models/filter.rb
# frozen_string_literal: true

class Filter < ApplicationRecord
end

app/models/hotel.rb
# frozen_string_literal: true

class Hotel < ApplicationRecord
  belongs_to :user
  belongs_to :location
  has_many_attached :images
  has_many :rooms, dependent: :destroy
  has_many :reviews
  def thumbnail(input)
    images[input].variant(resize: '600x300!').processed
  end

  belongs_to :location
  def self.search(search)
    if search
      where(['name LIKE ?', "%#{search}%"])
    else
      all
    end
  end
end

app/models/location.rb
# frozen_string_literal: true

class Location < ApplicationRecord
  has_many :hotels
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user
    belongs_to :hotel
end

app/models/role.rb
# frozen_string_literal: true

class Role < ApplicationRecord
  has_and_belongs_to_many :users, join_table: :users_roles

  belongs_to :resource,
             polymorphic: true,
             optional: true

  validates :resource_type,
            inclusion: { in: Rolify.resource_types },
            allow_nil: true

  scopify
end

app/models/room.rb
# frozen_string_literal: true

class Room < ApplicationRecord
  belongs_to :hotel
  has_many :room_bookings, dependent: :destroy
  has_many :bookings, through: :room_bookings
  belongs_to :category
  # attr_accessor :category_name

  # def category_name
  #   category.name
  # end

  def display_room
    room_number.to_s + '(' + category.name + ')' + '(' + 'price' + category.price.to_s + ')'
  end
  # belongs_to :room
  # accepts_nested_attributes_for :room, reject_if: :all_blank, allow_destroy: true
  scope :available_rooms, -> { where(availibility: true) }
end

app/models/room_booking.rb
# frozen_string_literal: true

class RoomBooking < ApplicationRecord
  belongs_to :booking
  belongs_to :room
  validates :check_in, presence: true
  validates :check_out, presence: true
  before_create :avail

  def avail; end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  rolify
  resourcify
  # include Authority::UserAbilities
  has_many :bookings, dependent: :destroy
  has_many :hotels
  has_many :reviews, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create :assign_default_role

  def assign_default_role
    add_role(:customer) if roles.blank?
  end

  def destroy
    update_attributes(deactivated: true) unless deactivated
    end

  def active_for_authentication?
    super && !deactivated
      end
end

app/models/users_role.rb
# frozen_string_literal: true

class UsersRole < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/helpers/bookings_helper.rb
# frozen_string_literal: true

module BookingsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/filters_helper.rb
# frozen_string_literal: true

module FiltersHelper
end

app/helpers/hotels_helper.rb
# frozen_string_literal: true

module HotelsHelper
end

app/helpers/locations_helper.rb
# frozen_string_literal: true

module LocationsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/rooms_helper.rb
# frozen_string_literal: true

module RoomsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Abrigo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <nav class="navbar navbar-expand-lg navbar-light bg-white border">
    <!-- <img src="/assets/logo.png" height="100px" width="100px"> -->
    
    <a class="navbar-brand text-success" href="/"><h2><b><i>Abrigo</h2></a>
    <% if current_user%>
    
     <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "btn btn-outline-success my-2 my-sm-0"%>
     <%# <h3 style="float: right">hello! <%= current_user.email%>
        <% else %>
        
        <%= link_to 'Sign up', new_user_registration_path,  class: "btn btn-outline-success my-2 my-sm-0" %>
        <%= link_to 'Sign in', new_user_session_path,  class: "btn btn-outline-success my-2 my-sm-0" %>
        <% end %>
        <%= link_to 'show hotel', hotels_path, class: "btn btn-outline-success my-2 my-sm-0" %>
        <% if current_user %>
        <%#= link_to 'Your bookings', user_index_path , class: "btn btn-outline-success my-2 my-sm-0" %>
        <% end %>
        <% if current_user && current_user.admin %>
          <%= link_to 'show user', users_path, class: "btn btn-outline-success my-2 my-sm-0" %>
          <%= link_to 'add hotel category', categories_path, class: "btn btn-outline-success my-2 my-sm-0" %>
           <%= link_to 'show bookings', room_bookings_path, class: "btn btn-outline-success my-2 my-sm-0" %>
            <%= link_to 'Insights', charts_path, class: "btn btn-outline-success my-2 my-sm-0" %>
        <% end %>


<%# <% if current_user && current_user.admin%>

 <%#= link_to 'show hotel', hotels_path, class: "btn btn-outline-success my-2 my-sm-0" %>
 <%# <%= link_to 'show user', users_path,  class: "btn btn-outline-success my-2 my-sm-0" %>
<%# end %> 
</nav>
    
<% if current_user %>
   <div class="d-flex justify-content-end">  <h5 class="text-light bg-success"> Hello,  <%= current_user.email %> </div></h5>
<% end %>
  </head>

  <body>
    <% render 'layouts/alerts' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
<title>PDFs - Ruby on Rails</title>
    <%= wicked_pdf_stylesheet_link_tag "application" %>
</head>
<body>
    <%= yield %>
</body>
</html>